import type { Order, DailyAnalytics, RestaurantProfile } from '@/types/orders'

const now = new Date()
const ago = (minutes: number) => new Date(now.getTime() - minutes * 60000).toISOString()

export const mockRestaurant: RestaurantProfile = {
  id: 'rest_01',
  name: 'The Stack Kitchen',
  timezone: 'Europe/London',
  platforms: ['uber_eats', 'deliveroo', 'just_eat', 'direct'],
}

export const mockOrders: Order[] = [
  {
    id: 'ord_001',
    display_id: '1247',
    platform: 'deliveroo',
    status: 'pending',
    customer_name: 'James T.',
    items: [
      { id: 'i1', name: 'Double Smash Burger', quantity: 2, price: 1290 },
      { id: 'i2', name: 'Loaded Fries', quantity: 1, price: 590 },
      { id: 'i3', name: 'Diet Coke', quantity: 2, price: 250 },
    ],
    subtotal: 3670,
    delivery_fee: 199,
    total: 3869,
    placed_at: ago(1),
    estimated_prep_minutes: 15,
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_002',
    display_id: '1246',
    platform: 'uber_eats',
    status: 'preparing',
    customer_name: 'Sarah M.',
    items: [
      { id: 'i4', name: 'Crispy Chicken Burger', quantity: 1, price: 1150 },
      { id: 'i5', name: 'Onion Rings', quantity: 1, price: 490 },
      { id: 'i6', name: 'Strawberry Shake', quantity: 1, price: 590 },
    ],
    subtotal: 2230,
    delivery_fee: 249,
    total: 2479,
    placed_at: ago(8),
    confirmed_at: ago(7),
    prep_started_at: ago(6),
    estimated_prep_minutes: 12,
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_003',
    display_id: '1245',
    platform: 'just_eat',
    status: 'preparing',
    customer_name: 'Ahmed K.',
    items: [
      { id: 'i7', name: 'BBQ Bacon Stack', quantity: 3, price: 1350 },
      { id: 'i8', name: 'Sweet Potato Fries', quantity: 2, price: 620 },
      { id: 'i9', name: 'Mineral Water', quantity: 3, price: 200 },
    ],
    subtotal: 5690,
    delivery_fee: 199,
    total: 5889,
    placed_at: ago(12),
    confirmed_at: ago(11),
    prep_started_at: ago(10),
    estimated_prep_minutes: 18,
    notes: 'No pickles on all burgers please',
    restaurant_id: 'rest_01',
    is_urgent: true,
  },
  {
    id: 'ord_004',
    display_id: '1244',
    platform: 'deliveroo',
    status: 'ready',
    customer_name: 'Emma L.',
    items: [
      { id: 'i10', name: 'Veggie Smash', quantity: 2, price: 1190 },
      { id: 'i11', name: 'Truffle Fries', quantity: 2, price: 690 },
    ],
    subtotal: 3760,
    delivery_fee: 199,
    total: 3959,
    placed_at: ago(22),
    confirmed_at: ago(21),
    prep_started_at: ago(19),
    ready_at: ago(4),
    estimated_prep_minutes: 15,
    driver: { name: 'Marcus D.', eta_minutes: 3, rating: 4.9 },
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_005',
    display_id: '1243',
    platform: 'uber_eats',
    status: 'picked_up',
    customer_name: 'Chen W.',
    items: [
      { id: 'i12', name: 'Classic Smash', quantity: 2, price: 1090 },
      { id: 'i13', name: 'Cheese Dog', quantity: 1, price: 890 },
      { id: 'i14', name: 'Loaded Fries', quantity: 2, price: 590 },
      { id: 'i15', name: 'Vanilla Shake', quantity: 1, price: 590 },
    ],
    subtotal: 4840,
    delivery_fee: 249,
    total: 5089,
    placed_at: ago(35),
    confirmed_at: ago(34),
    prep_started_at: ago(32),
    ready_at: ago(18),
    picked_up_at: ago(12),
    estimated_prep_minutes: 14,
    driver: { name: 'Priya S.', eta_minutes: 8, rating: 4.7 },
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_006',
    display_id: '1242',
    platform: 'direct',
    status: 'confirmed',
    customer_name: 'Oliver B.',
    items: [
      { id: 'i16', name: 'Family Bundle', quantity: 1, price: 3490 },
      { id: 'i17', name: 'Extra Sauce Set', quantity: 1, price: 290 },
    ],
    subtotal: 3780,
    delivery_fee: 0,
    total: 3780,
    placed_at: ago(4),
    confirmed_at: ago(3),
    estimated_prep_minutes: 20,
    notes: 'Please ring doorbell twice',
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_007',
    display_id: '1241',
    platform: 'just_eat',
    status: 'preparing',
    customer_name: 'Zara H.',
    items: [
      { id: 'i18', name: 'Spicy Jalapeño Burger', quantity: 2, price: 1290 },
      { id: 'i19', name: 'Loaded Fries', quantity: 1, price: 590 },
    ],
    subtotal: 3170,
    delivery_fee: 199,
    total: 3369,
    placed_at: ago(14),
    confirmed_at: ago(13),
    prep_started_at: ago(11),
    estimated_prep_minutes: 13,
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_008',
    display_id: '1240',
    platform: 'deliveroo',
    status: 'delivered',
    customer_name: 'Tom R.',
    items: [
      { id: 'i20', name: 'Double Smash Burger', quantity: 1, price: 1290 },
      { id: 'i21', name: 'Classic Fries', quantity: 1, price: 390 },
      { id: 'i22', name: 'Coke', quantity: 1, price: 250 },
    ],
    subtotal: 1930,
    delivery_fee: 199,
    total: 2129,
    placed_at: ago(58),
    confirmed_at: ago(57),
    prep_started_at: ago(55),
    ready_at: ago(42),
    picked_up_at: ago(38),
    delivered_at: ago(25),
    estimated_prep_minutes: 13,
    driver: { name: 'David K.', rating: 4.8 },
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_009',
    display_id: '1239',
    platform: 'uber_eats',
    status: 'pending',
    customer_name: 'Fatima A.',
    items: [
      { id: 'i23', name: 'Crispy Chicken Burger', quantity: 1, price: 1150 },
      { id: 'i24', name: 'Sweet Potato Fries', quantity: 1, price: 620 },
      { id: 'i25', name: 'Oreo Shake', quantity: 1, price: 690 },
    ],
    subtotal: 2460,
    delivery_fee: 249,
    total: 2709,
    placed_at: ago(0),
    estimated_prep_minutes: 12,
    restaurant_id: 'rest_01',
  },
  {
    id: 'ord_010',
    display_id: '1238',
    platform: 'direct',
    status: 'preparing',
    customer_name: 'Harry P.',
    items: [
      { id: 'i26', name: 'Double Smash Burger', quantity: 4, price: 1290 },
      { id: 'i27', name: 'Loaded Fries', quantity: 4, price: 590 },
      { id: 'i28', name: 'Soft Drinks', quantity: 4, price: 250 },
    ],
    subtotal: 8520,
    delivery_fee: 0,
    total: 8520,
    placed_at: ago(16),
    confirmed_at: ago(15),
    prep_started_at: ago(13),
    estimated_prep_minutes: 20,
    notes: 'Large office order — label bags separately',
    restaurant_id: 'rest_01',
    is_urgent: true,
  },
]

export const mockAnalytics: DailyAnalytics = {
  date: new Date().toISOString().split('T')[0],
  total_orders: 47,
  revenue: 189430,
  avg_prep_time_minutes: 13.4,
  on_time_rate: 94.2,
  cancelled_orders: 2,
  platform_breakdown: [
    { platform: 'uber_eats', orders: 18, revenue: 71240 },
    { platform: 'deliveroo', orders: 16, revenue: 62190 },
    { platform: 'just_eat', orders: 9, revenue: 34560 },
    { platform: 'direct', orders: 4, revenue: 21440 },
  ],
}
